### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by turgeonmaxime** [sahirbhatnagar/cbpaper#16]
Last week I finished writing the discussion, and so we're very close to a complete first draft. Here are the last few things to do:

- [x] Write introduction
- [x] Update literature review for competing risk models
- [x] Finish section on implementation with a few paragraph on population-time plots.

I'm taking care of the first two; I think @sahirbhatnagar is writing the third one. @Jesse-Islam You also have a few comments to address in the text (I wrote them in red), both in the Literature review and the Support case study.

There are a few other things that I would like to get your opinion on.

  1. In the Support case study, there are two large tables that describe the variables in the dataset. I think it would make more sense to move this to an appendix, since we're not actually referring to them in the text.
  2. I don't think the comparison with Kaplan-Meier the Support case-study makes much sense, since the Coxnet and case-base approaches estimate something quite different.
  3. I suggest we keep the code for population-time plots (as it is a feature of `casebase`) but hide the code for the other graphs. It would make the manuscript shorter and a bit more readable.
  4. The manuscript is quite long, so we may consider removing one case-study. I think the two most obvious candidates for removal are the Bone-marrow transplant (competing risks) and Stanford Heart transplant (non-proportional hazard). We don't have to take a decision about this right now, we can wait until a later draft.

**Comment by turgeonmaxime** [comment]
Let me know what you think, in the meantime I'll be working on the introduction.

**Comment by sahirbhatnagar** [comment]
Yes I agree. Let's aim to wrap this up ASAP. I am writing the `popTime` section. 

1. OK. Jesse is figuring out a way to visualize the coefficients instead of the tables
2. We decided to change the curve being plotted for both coxnet and casebase. Instead of plotting the curve for an individual, we are calculating the risk curve for all patients, and then plotting the average across all patients, so that comparison with KM makes sense. Jesse will be describing this in the paper. 
3. OK.
4. We can remove some case-studies, but lets get the first draft completed, with only the necessary code showing to see the length. 

Other things to be done:

- [ ] build a `pkgdown` website for `casebase` package
- [ ] prepare for updated CRAN release. Note that the CRAN requirement have gotten much stricter, so this might take some more time than usual. Even if Travis checks pass, there is a stronger chance than before, that our package may be rejected. This iterative process can take time.

**Comment by Jesse-Islam** [comment]
I've answered most of the red comments and am im progress completing IPA and a nice figure for variable comparison. I'll upload everything I've done so far as soon as IPA is complete.

**Comment by turgeonmaxime** [comment]
I just re-read your TODO list @sahirbhatnagar, and I'm wondering how a `pkgdown` website would be different than what we have? http://sahirbhatnagar.com/casebase/ How easy would it be to transition to `pkgdown`?
